---
- name: Déployer Docker et WordPress sur Kali (Debian)
  hosts: kali
  become: yes

  vars:
    wp_dir: /opt/wordpress
    mysql_root_password: rootpassword
    mysql_database: wordpress
    mysql_user: wpuser
    mysql_password: wppassword

  tasks:
    # Installation Docker
    - name: Installer les dépendances
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
        update_cache: yes

    - name: Installer Docker Engine (docker.io pour Kali)
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Installer Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/download/v2.12.2/docker-compose-linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Ajouter l'utilisateur au groupe docker
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Démarrer et activer Docker
      service:
        name: docker
        state: started
        enabled: yes

    # Déploiement WordPress
    - name: Créer le répertoire WordPress
      file:
        path: "{{ wp_dir }}"
        state: directory
        mode: '0755'

    - name: Générer le docker-compose.yml
      template:
        src: templates/docker-compose.yml.j2
        dest: "{{ wp_dir }}/docker-compose.yml"
        mode: '0644'

    - name: Lancer WordPress avec Docker Compose
      shell: docker-compose up -d
      args:
        chdir: "{{ wp_dir }}"
        creates: "{{ wp_dir }}/.deployed"

    - name: Marquer comme déployé
      file:
        path: "{{ wp_dir }}/.deployed"
        state: touch
        mode: '0644'
